# Generated by Django 3.2.25 on 2026-02-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_booking_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('service', 'date', 'time'), name='unique_service_booking'),
        ),
    ]
