# Generated by Django 3.2.25 on 2026-02-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_booking_unique_service_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
